kind: PipelineRun
apiVersion: tekton.dev/v1
metadata:
  name: custom-tests
spec:
  taskRunSpecs:
  - pipelineTaskName: run-integration-tests
    stepSpecs:
      - name: run-tests
        computeResources:
          requests:
            cpu: 2
            memory: 4Gi
          limits:
            cpu: 2
            memory: 4Gi
  pipelineSpec:
    # params:
    #   - description: 'Snapshot of the application'
    #     name: SNAPSHOT
    #     type: string
    tasks:
      - name: run-test
        image: registry.fedoraproject.org/fedora-minimal:42
        script: |
          echo run tests

