apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: test
spec:
  params:
  - name: SNAPSHOT
    description: 'Snapshot of the application'
    default: ''
    type: string
  tasks:
  - name: test
    params:
    - name: SNAPSHOT
      value: $(params.SNAPSHOT)
    taskSpec:
      steps:
      - name: test
        # image: quay.io/konflux-ci/task-runner:1.6.0@sha256:1abfe4e50d4e961d0fd9790202565f93ee650fe8dfc50932c94989acba10485f
        image: registry.fedoraproject.org/fedora:42
        script: |
          set -x
          dnf install --quiet --no-docs --disable-repo=fedora-cisco-openh264 -y podman
          id
          podman --version
          podman run \
            --cgroups=disabled \
            --network none \
            --storage-driver vfs \
            --rm registry.fedoraproject.org/fedora-minimal:42 echo hello
        securityContext:
          capabilities:
            add:
              - "SETFCAP"
          runAsUser: 1000
          runAsGroup: 1000
